spring:
  application:
    name: server2
  kafka:
    bootstrap-servers: 192.168.182.100:9092
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
      group-id: qianxin_test1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://192.168.182.102:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    druid:
      max-wait: 6000
      min-idle: 6
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'X'
      test-while-idle: false
      pool-prepared-statements: true
server:
  port: 8082
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8888/eureka/
