spring:
  application:
    name: server1
  kafka:
    bootstrap-servers: 192.168.47.101:9092
    producer:
      acks: 1
      buffer-memory: 4000
      batch-size: 2000
      retries: 0
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8080/eureka/
server:
  port: 8081
