spring:
  application:
    name: server1
  kafka:
    bootstrap-servers: 192.168.47.101:9092
    producer:
      acks: 1
      buffer-memory: 33554432
      batch-size: 16384
      retries: 0
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8888/eureka/
server:
  port: 8081
